name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    name: Typecheck, Test and Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "pnpm"

      - name: Enable corepack (pnpm)
        run: |
          corepack enable
          # Activate pnpm shim so the pnpm executable is available on the runner
          corepack prepare pnpm@latest --activate

      - name: Verify pnpm is available
        run: pnpm -v

      - name: Install pnpm
        run: corepack prepare pnpm@latest --activate

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Typecheck
        run: pnpm typecheck

      - name: Run tests
        run: pnpm test -- --reporter=dot

      - name: Build
        run: pnpm build
